version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
    
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8585:80"
        volumes:
            - ./:var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
    
    mysql:
        image: mysql:8.0.32
        restart: unless-stoped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
